# Generated by Django 5.1.6 on 2025-03-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=4000, null=True)),
                ('subtitle', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateField()),
                ('file', models.FileField(max_length=400, upload_to='audio/teachings/')),
            ],
        ),
    ]
