# Generated by Django 5.1.6 on 2025-03-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaching',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='teaching',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='file',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to='audio/teachings/'),
        ),
    ]
