# Generated by Django 5.1.6 on 2025-03-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_name_teaching_title_alter_teaching_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='image',
            field=models.ImageField(blank=True, max_length=400, null=True, upload_to='teachings/images'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='file',
            field=models.FileField(blank=True, max_length=400, null=True, upload_to='teachings/audio/'),
        ),
    ]
