# Generated by Django 5.1.7 on 2025-03-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_teaching_image_alter_teaching_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=4000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, max_length=400, null=True, upload_to='teachings/images')),
            ],
        ),
    ]
