# Generated by Django 5.1.7 on 2025-03-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.series')),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.teaching')),
            ],
        ),
        migrations.AddField(
            model_name='teaching',
            name='series',
            field=models.ManyToManyField(through='posts.SeriesPart', to='posts.series'),
        ),
    ]
